---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Chrony must be running
      ansible.builtin.service_facts:
      register: common_verify_services

    - name: Assert chrony is active
      ansible.builtin.assert:
        that:
          - common_verify_services.ansible_facts.services['chrony.service'].state == 'running'

    - name: Ufw must be enabled
      ansible.builtin.command: ufw status
      register: common_verify_ufw_status
      changed_when: false
      failed_when: "'Status: active' not in common_verify_ufw_status.stdout"
